export enum LoadContext {
  PUBLIC_CODE_BLOCKS = 'PUBLIC_CODE_BLOCKS',
  PRIVATE_CODE_BLOCKS = 'PRIVATE_CODE_BLOCKS',
  FAVORITES_CODE_BLOCKS = 'FAVORITES_CODE_BLOCKS',
  SHARED_CODE_BLOCKS = 'SHARED_CODE_BLOCKS',
  CODE_BLOCK_VIEW = 'CODE_BLOCK_VIEW',
  CODE_BLOCK_EDIT = 'CODE_BLOCK_EDIT'
}
